<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Jellyfin.Plugin.VidaaBack</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.VidaaBack</RootNamespace>
    <Version>0.1.2</Version>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Jellyfin.Controller" Version="10.11.5" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.5" ExcludeAssets="runtime" />
    <EmbeddedResource Include="vidaa-back.js" />
    <EmbeddedResource Include="Configuration\configPage.html" />
  </ItemGroup>
</Project>
